version: '3'

services:
  app:
    container_name: ${APP_NAME}
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/
      - APACHE_LOG_DIR=/var/www/html/logs
      - APP_DOMAIN=localhost
      - TZ=Asia/Tokyo
    tty: true
    ports:
      - ${APP_PORT:-80}:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  
  db:
    container_name: ${DB_NAME}
    image: postgres:9.2
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=Asia/Tokyo
    tty: true
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/initdb/:/docker-entrypoint-initdb.d
      - ./docker/db/storage:/var/lib/postgresql/data
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  storage:
